SELECT /*+ ORDERED */ W1.SID  WAITING_SESSION,
        H1.SID  HOLDING_SESSION,
        W.KGLLKTYPE LOCK_OR_PIN,
        W.KGLLKHDL ADDRESS,
        DECODE(H.KGLLKMOD,  0, 'NONE', 1, 'NULL', 2, 'SHARE', 3, 'EXCLUSIVE', 'UNKNOWN') MODE_HELD,
        DECODE(W.KGLLKREQ,  0, 'NONE', 1, 'NULL', 2, 'SHARE', 3, 'EXCLUSIVE', 'UNKNOWN') MODE_REQUESTED
  FROM DBA_KGLLOCK W, DBA_KGLLOCK H, V$SESSION W1, V$SESSION H1
 WHERE
  (
   ((H.KGLLKMOD != 0) AND (H.KGLLKMOD != 1)
     AND ((H.KGLLKREQ = 0) OR (H.KGLLKREQ = 1))
     )
   AND
     (
       ((W.KGLLKMOD = 0) OR (W.KGLLKMOD= 1))
       AND ((W.KGLLKREQ != 0) AND (W.KGLLKREQ != 1))
     )
  )
  AND  W.KGLLKTYPE         =  H.KGLLKTYPE
  AND  W.KGLLKHDL         =  H.KGLLKHDL
  AND  W.KGLLKUSE     =   W1.SADDR
  AND  H.KGLLKUSE     =   H1.SADDR
;
