col INPUT_BYTES_DISPLAY for a10
col OUTPUT_BYTES_DISPLAY for a10
col INPUT_BYTES_PER_SEC_DISPLAY for a10
col OUTPUT_BYTES_PER_SEC_DISPLAY for a10
col TIME_TAKEN_DISPLAY for a10
select * from V$RMAN_BACKUP_JOB_DETAILS order by START_TIME;
